version: '3.9'
services:
  backend:
    build: .
    container_name: backend
    working_dir: /user-registration/backend
    ports:
      - "3000:3000"
    command: npm run start
    volumes:
      - .:/user-registration

  frontend:
    build: .
    container_name: frontend
    working_dir: /user-registration/frontend
    ports:
      - "3001:3001"
    command: yarn start
    volumes:
      - .:/user-registration

  db:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 
      POSTGRES_DATABASE: Users